src/config/routes.rb
Rails.application.routes.draw do
  get 'login/index'

  resources :reservations
  resources :tokens
  resources :trainers
  resources :customers
  resources :companies
  resources :users

  get '/' => 'login#index'

  controller :login do
    post 'login/login' => :login, as: 'login'
    post 'login/dupEmail' => :dup_email, as: 'dupEmail'
    post 'login/updatePassword' => :update_password, as: 'updatePassword'
  end

  controller :reservations do
    get 'reservations/customer/:customer_id/date/:date' => :customer_list_date, as: 'customerListByDate'
    get 'reservations/customer/:customer_id/week/:date' => :customer_list_week, as: 'customerListByWeek'
    get 'reservations/customer/:customer_id/month/:year/:month/' => :customer_list_month, as: 'customerListByMonth'
    post 'reservations/add' => :add, as: 'addReservation'

    get 'reservations/trainer/:trainer_id/date/:date' => :trainer_list_date, as: 'trainerListByDate'
    get 'reservations/trainer/:trainer_id/week/:date' => :trainer_list_week, as: 'trainerListByWeek'
    get 'reservations/trainer/:trainer_id/month/:year/:month/' => :trainer_list_month, as: 'trainerListByMonth'

  end

  controller :customers do
    get 'trainers/:trainer_id/customers' => :get_customer_by_trainer, as: 'customerListByTrainerId'
  end

  controller :users do
    put 'users/update/withPassword' => :updateWithPassword, as: 'updateWithPassword'
    put 'users/update/info'=> :update, as: 'updateUser'
  end

end

src/app/models/trainer.rb
class Trainer < ActiveRecord::Base
  belongs_to :user
  belongs_to :company

  has_many :customer
  has_many :reservation

  attr_accessor :email,:password,:name,:sex,:tel
end

src/app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy]

  # GET /trainers
  # GET /trainers.json
  def index
    @trainers = Trainer.all
  end

  def list
    @trainers = Trainer.all
    render :json => @trainers,:include => [:company,:user] ,status: :ok
  end
  # GET /trainers/1
  # GET /trainers/1.json
  def show
    render :json => @trainer,:include => [:company,:user] ,status: :ok
    @company_form = {company_name: @trainer.company.name, company_tel: @trainer.company.tel, company_address: @trainer.company.address}
  end

  # GET /trainers/new
  def new
    @trainer = Trainer.new
    @user = User.new
  end

  # GET /trainers/1/edit
  def edit
    @trainer.name = @trainer.user.name
    @trainer.email = @trainer.user.email
    @trainer.tel = @trainer.user.tel
    @trainer.sex = @trainer.user.sex
  end

  # POST /trainers
  # POST /trainers.json
  def create

    @user = User.new(users_params)
    @user.save
    @trainer = Trainer.new(trainer_params)
    @trainer.user_id = @user.id
    @trainer.created_at = @user.created_at
    @trainer.updated_at = @user.updated_at

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to '/trainers', notice: 'Trainer was successfully created.' }
        format.json { render :show, status: :created, location: @trainer }
      else
        format.html { render :new }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    trainer = Trainer.find(params[:id])
    user = User.find(trainer.user_id)
    user.name = params[:trainer][:name]
    user.email = params[:trainer][:email]
    user.tel = params[:trainer][:tel]
    user.sex = params[:trainer][:sex]
    if params[:trainer][:password].length>0
      user.password = Digest::SHA1.hexdigest(params[:trainer][:password])
    end
    respond_to do |format|
      if trainer.save and user.save
        format.html { redirect_to '/trainers', notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: trainer }
      else
        format.html { render :new }
        format.json { render json: trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    if @trainer.is_delete == 1
      user_id = @trainer.user_id
      @trainer.destroy
      User.destroy(user_id)
    else
      @trainer.is_delete = 1
      @trainer.save
    end
    respond_to do |format|
      format.html { redirect_to trainers_url, notice: 'Trainer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_trainer
    @trainer = Trainer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def trainer_params
    params.require(:trainer).permit(:user_id, :company_id)
  end

  def users_params
    params.require(:trainer).permit(:email, :password, :name, :tel, :sex)
  end
end

src/app/helpers/trainers_helper.rb
module TrainersHelper
end

src/app/views/trainers/_form.html.erb
<%= form_for(@trainer) do |f| %>
    <% if @trainer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>

          <ul>
            <% @trainer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :company_id %><br>
      <%= f.select :company_id, Company.where('is_delete = false').collect{ |c| [c.name, c.id]} %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.email_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :tel %><br>
      <%= f.telephone_field :tel %>
    </div>
    <div class="field">
      <%= f.label :sex %><br>
      남 <%= f.radio_button :sex, 1 %>
      여 <%= f.radio_button :sex, 2 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

src/app/views/trainers/edit.html.erb
<h1>Editing Trainer</h1>

<%= render 'form' %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', trainers_path %>

src/app/views/trainers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trainers</h1>

<table>
  <thead>
  <tr>
    <th>Company</th>
    <th>Name</th>
    <th>Email</th>
    <th>Tel</th>
    <th>Sex</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @trainers.each do |trainer| %>
      <% if trainer.is_delete == 1 %>
          <tr class="text-danger">
      <% else %>
          <tr>
      <% end %>
      <td><%= trainer.company.name %></td>
      <td><%= trainer.user.name %></td>
      <td><%= trainer.user.email %></td>
      <td><%= trainer.user.tel %></td>
      <td><%= trainer.user.sex %></td>
      <td><%= link_to 'Show', trainer %></td>
      <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
      <td><%= link_to 'Destroy', trainer, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trainer', new_trainer_path %>

src/app/views/trainers/new.html.erb
<h1>New Trainer</h1>

<%= render 'form' %>

<%= link_to 'Back', trainers_path %>

src/app/views/trainers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trainer.user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @trainer.user.email %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @trainer.user.tel %>
</p>

<p>
  <strong>Company:</strong>
  <%= @trainer.company.name %>
</p>

<%= link_to 'Edit', edit_trainer_path(@trainer) %> |
<%= link_to 'Back', trainers_path %>