src/config/routes.rb
Rails.application.routes.draw do
  get 'login/index'

  resources :reservations
  resources :tokens
  resources :trainers
  resources :customers
  resources :companies
  resources :users

  get '/' => 'login#index'

  controller :login do
    post 'login/login' => :login, as: 'login'
    post 'login/dupEmail' => :dup_email, as: 'dupEmail'
    post 'login/updatePassword' => :update_password, as: 'updatePassword'
  end

  controller :reservations do
    get 'reservations/customer/:customer_id/date/:date' => :customer_list_date, as: 'customerListByDate'
    get 'reservations/customer/:customer_id/week/:date' => :customer_list_week, as: 'customerListByWeek'
    get 'reservations/customer/:customer_id/month/:year/:month/' => :customer_list_month, as: 'customerListByMonth'
    post 'reservations/add' => :add, as: 'addReservation'

    get 'reservations/trainer/:trainer_id/date/:date' => :trainer_list_date, as: 'trainerListByDate'
    get 'reservations/trainer/:trainer_id/week/:date' => :trainer_list_week, as: 'trainerListByWeek'
    get 'reservations/trainer/:trainer_id/month/:year/:month/' => :trainer_list_month, as: 'trainerListByMonth'

  end

  controller :customers do
    get 'trainers/:trainer_id/customers' => :get_customer_by_trainer, as: 'customerListByTrainerId'
  end

  controller :users do
    put 'users/update/withPassword' => :updateWithPassword, as: 'updateWithPassword'
    put 'users/update/info'=> :update, as: 'updateUser'
  end

end

src/app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :trainer
  belongs_to :customer
end

src/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]


# date format = 'yyyy-mm-dd'

  def customer_list_date
    @reservations = Reservation.where("customer_id = ? and DATE(start_datetime) = ?", params[:customer_id], params[:date]).order("start_datetime ASC")
    render :json => @reservations, status: :ok
  end

  def customer_list_week
    time = Time.zone.parse(params[:date]+ " 00:00:00")

    startDateWeek = time.beginning_of_week
    endDateWeek = time.beginning_of_week + 7.days
    @reservations = Reservation.where("customer_id = ? and start_datetime>=? and start_datetime<?", params[:customer_id], startDateWeek, endDateWeek).order("start_datetime ASC")

    render :json => @reservations, status: :ok

  end

  def customer_list_month
    @reservations = Reservation.where("customer_id = ? and YEAR(start_datetime) = ? and MONTH(start_datetime) = ?", params[:customer_id], params[:year], params[:month]).order("start_datetime ASC")
    render :json => @reservations, status: :ok
  end


  def trainer_list_date
    @reservations = Reservation.where("trainer_id = ? and DATE(start_datetime) = ?", params[:trainer_id], params[:date]).order("start_datetime ASC")
    render :json => @reservations, status: :ok
  end

  def trainer_list_week
    time = Time.zone.parse(params[:date]+ " 00:00:00")

    startDateWeek = time.beginning_of_week
    endDateWeek = time.beginning_of_week + 7.days
    @reservations = Reservation.where("trainer_id = ? and start_datetime>=? and start_datetime<?", params[:trainer_id], startDateWeek, endDateWeek).order("start_datetime ASC")

    render :json => @reservations, status: :ok

  end

  def trainer_list_month
    @reservations = Reservation.where("trainer_id = ? and YEAR(start_datetime) = ? and MONTH(start_datetime) = ?", params[:trainer_id], params[:year], params[:month]).order("start_datetime ASC")
    render :json => @reservations, status: :ok
  end


# GET /reservations
# GET /reservations.json
  def index
    @reservations = Reservation.all
  end

# GET /reservations/1
# GET /reservations/1.json
  def show
    render :json => @reservation, :include => {:customer => {:include => :user}}, status: :ok
  end

# GET /reservations/new
  def new
    @reservation = Reservation.new
  end

# GET /reservations/1/edit
  def edit
  end

# POST /reservations
# POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  def add
    customer = Customer.find(params[:customer_id])
    if customer.pt_count >=1
      customer.pt_count-=1
      @reservation = Reservation.new(reservation_add_params)
      @reservation.customer_id = params[:customer_id]
      @reservation.trainer_id = params[:trainer_id]
      if @reservation.save and customer.save
        render :json => @reservation, status: :created
      else
        render json: @reservation.errors, status: :unprocessable_entity
      end
    else
      render json: @reservation.errors, status: :unprocessable_entity
    end
  end

# PATCH/PUT /reservations/1
# PATCH/PUT /reservations/1.json
  def update
    if @reservation.update(reservation_add_params)
      render :json => @reservation, status: :ok
    else
      render json: @reservation.errors, status: :unprocessable_entity
    end
  end

# DELETE /reservations/1
# DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
# Use callbacks to share common setup or constraints between actions.
  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

# Never trust parameters from the scary internet, only allow the white list through.
  def reservation_params
    params.require(:reservation).permit(:is_delete, :trainer_id, :customer_id, :start_datetime, :end_datetime, :memo)
  end

  def reservation_add_params
    params.require(:reservation).permit(:is_delete, :start_datetime, :end_datetime, :memo)
  end

end

src/app/helpers/reservations_helper.rb
module ReservationsHelper
end

src/app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :is_delete %><br>
    <%= f.number_field :is_delete %>
  </div>
  <div class="field">
    <%= f.label :trainer_id %><br>
    <%= f.text_field :trainer_id %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.text_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :start_datetime %><br>
    <%= f.text_field :start_datetime %>
  </div>
  <div class="field">
    <%= f.label :end_datetime %><br>
    <%= f.text_field :end_datetime %>
  </div>
    <div class="field">
      <%= f.label :memo %><br>
      <%= f.text_field :memo %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

src/app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Is delete</th>
      <th>Trainer</th>
      <th>Customer</th>
      <th>Start datetime</th>
      <th>End datetime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.is_delete %></td>
        <td><%= reservation.trainer %></td>
        <td><%= reservation.customer %></td>
        <td><%= reservation.start_datetime %></td>
        <td><%= reservation.end_datetime %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

src/app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

src/app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Is delete:</strong>
  <%= @reservation.is_delete %>
</p>

<p>
  <strong>Trainer:</strong>
  <%= @reservation.trainer %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @reservation.customer %>
</p>

<p>
  <strong>Start datetime:</strong>
  <%= @reservation.start_datetime %>
</p>

<p>
  <strong>End datetime:</strong>
  <%= @reservation.end_datetime %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>