src/config/routes.rb
Rails.application.routes.draw do
  get 'login/index'

  resources :reservations
  resources :tokens
  resources :trainers
  resources :customers
  resources :companies
  resources :users

  get '/' => 'login#index'

  controller :login do
    post 'login/login' => :login, as: 'login'
    post 'login/dupEmail' => :dup_email, as: 'dupEmail'
    post 'login/updatePassword' => :update_password, as: 'updatePassword'
  end

  controller :reservations do
    get 'reservations/customer/:customer_id/date/:date' => :customer_list_date, as: 'customerListByDate'
    get 'reservations/customer/:customer_id/week/:date' => :customer_list_week, as: 'customerListByWeek'
    get 'reservations/customer/:customer_id/month/:year/:month/' => :customer_list_month, as: 'customerListByMonth'
    post 'reservations/add' => :add, as: 'addReservation'

    get 'reservations/trainer/:trainer_id/date/:date' => :trainer_list_date, as: 'trainerListByDate'
    get 'reservations/trainer/:trainer_id/week/:date' => :trainer_list_week, as: 'trainerListByWeek'
    get 'reservations/trainer/:trainer_id/month/:year/:month/' => :trainer_list_month, as: 'trainerListByMonth'

  end

  controller :customers do
    get 'trainers/:trainer_id/customers' => :get_customer_by_trainer, as: 'customerListByTrainerId'
  end

  controller :users do
    put 'users/update/withPassword' => :updateWithPassword, as: 'updateWithPassword'
    put 'users/update/info'=> :update, as: 'updateUser'
  end

end

src/app/models/company.rb
class Company < ActiveRecord::Base
  has_many :trainer
end

src/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    if(@company.is_delete == 1)
      @company.destroy
    else
      @company.is_delete = 1
      @company.save
    end
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :tel, :address, :url)
    end
end

src/app/helpers/companies_helper.rb
module CompaniesHelper
end

src/app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.telephone_field :tel %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.url_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

src/app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tel</th>
      <th>Address</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @companies.each do |company| %>
      <% if company.is_delete == 1%>
      <tr class="text-danger">
      <% else %>
      <tr>
      <% end %>
        <td><%= company.name %></td>
        <td><%= company.tel %></td>
        <td><%= company.address %></td>
        <td><%= company.url %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

src/app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

src/app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @company.tel %>
</p>

<p>
  <strong>Address:</strong>
  <%= @company.address %>
</p>

<p>
  <strong>Url:</strong>
  <%= @company.url %>
</p>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>